import { db, getLogin } from './auth-utils.js';
import { doc, getDoc, setDoc, serverTimestamp } from 'https://www.gstatic.com/firebasejs/10.12.0/firebase-firestore.js';

const REF=doc(db,'vereinsspielserie','hauptserie');
const ROUNDS=['Achtelfinale','Viertelfinale','Halbfinale','Finale'];
const defaultRound={Achtelfinale:{sets:1,legs:3},Viertelfinale:{sets:1,legs:3},Halbfinale:{sets:1,legs:4},Finale:{sets:1,legs:5}};
let state={config:{name:'Vereins-Premier-League',maxPlayers:16,out:'Double Out',rounds:defaultRound},players:[],ranking:{},days:[],current:null};
const user=getLogin(); const isAdmin=['admin','captain'].includes(String(user?.rolle||'').toLowerCase());
const $=id=>document.getElementById(id);
function toast(m){const t=$('toast');t.textContent=m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2400)}
function uid(){return crypto.randomUUID?.()||Math.random().toString(36).slice(2)}
function esc(s){return String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
async function save(){await setDoc(REF,{...state,updatedAt:serverTimestamp()});renderAll()}
async function load(){const s=await getDoc(REF);if(s.exists()) state={...state,...s.data()};renderAll()}
function rankRows(){return state.players.map(p=>({p,...(state.ranking[p.id]||{})})).map(x=>({...x,points:x.points||0,days:x.days||0,wins:x.wins||0,titles:x.titles||0,legsFor:x.legsFor||0,legsAgainst:x.legsAgainst||0})).sort((a,b)=>b.points-a.points||b.titles-a.titles||(b.legsFor-b.legsAgainst)-(a.legsFor-a.legsAgainst)||a.p.name.localeCompare(b.p.name));}
function renderAll(){document.querySelectorAll('.admin-only').forEach(el=>el.hidden=!isAdmin);renderConfig();renderPlayers();renderRanking();renderCurrent();}
function renderConfig(){const c=state.config;$('configName').value=c.name||'';$('maxPlayers').value=c.maxPlayers||16;$('gameOut').value=c.out||'Double Out';$('serieName').textContent=c.name||'Vereins-Premier-League';$('serieMeta').textContent=`Bis ${c.maxPlayers||16} Spieler · ${c.out||'Double Out'}`;$('spieltagNummer').textContent=`${state.days.length} Spieltage`;const box=$('roundSettings');box.innerHTML=ROUNDS.map(r=>`<div class="round-setting"><strong>${r}</strong><label>Gewinn-Sets<input data-round="${r}" data-key="sets" type="number" min="1" max="9" value="${c.rounds?.[r]?.sets||1}"></label><label>Gewinn-Legs je Set<input data-round="${r}" data-key="legs" type="number" min="1" max="15" value="${c.rounds?.[r]?.legs||3}"></label></div>`).join('');}
function renderPlayers(){const list=$('playersAdmin');list.innerHTML=state.players.length?state.players.map(p=>`<div class="player-admin-row"><span>${esc(p.name)}</span><button data-remove="${p.id}">Entfernen</button></div>`).join(''):'<p class="hint">Noch keine Spieler angelegt.</p>';list.querySelectorAll('[data-remove]').forEach(b=>b.onclick=async()=>{if(state.current)return toast('Laufenden Spieltag zuerst abschließen.');state.players=state.players.filter(p=>p.id!==b.dataset.remove);delete state.ranking[b.dataset.remove];await save()});$('attendanceList').innerHTML=state.players.map(p=>`<label class="attendance-row"><span>${esc(p.name)}</span><input type="checkbox" data-attend="${p.id}" checked></label>`).join('');}
function renderRanking(){const rows=rankRows();$('rankingBody').innerHTML=rows.length?rows.map((x,i)=>`<tr><td>${i+1}</td><td>${esc(x.p.name)}</td><td>${x.days}</td><td>${x.wins}</td><td>${x.titles}</td><td>${x.legsFor}:${x.legsAgainst}</td><td>${x.legsFor-x.legsAgainst}</td><td><strong>${x.points}</strong></td></tr>`).join(''):'<tr><td colspan="8">Noch keine Teilnehmer oder Ergebnisse.</td></tr>';}
function bracketSize(n){return n<=4?4:n<=8?8:16}
function seededOrder(ids){const r=rankRows().filter(x=>ids.includes(x.p.id)).map(x=>x.p.id);const order=[];let l=0,h=r.length-1;while(l<=h){order.push(r[l++]);if(l<=h)order.push(r[h--]);}return order}
function shuffle(a){a=[...a];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function makeBracket(ids,drawMode,byeMode){const size=bracketSize(ids.length), byeCount=size-ids.length;let ordered=drawMode==='ranking'?seededOrder(ids):shuffle(ids);let byes=byeMode==='ranking'?rankRows().filter(x=>ids.includes(x.p.id)).map(x=>x.p.id).slice(0,byeCount):shuffle(ids).slice(0,byeCount);let slots=Array(size).fill(null), available=[...Array(size).keys()];const byeSlots=[];for(let i=0;i<byeCount;i++)byeSlots.push(i*2);byes.forEach((id,i)=>{slots[byeSlots[i]]=id;ordered=ordered.filter(x=>x!==id)});available=available.filter(i=>!byeSlots.includes(i));shuffle(available).forEach((slot,i)=>{if(ordered[i])slots[slot]=ordered[i]});const firstRound=size===16?'Achtelfinale':size===8?'Viertelfinale':'Halbfinale';const rounds=ROUNDS.slice(ROUNDS.indexOf(firstRound));const matches={};rounds.forEach((r,ri)=>{matches[r]=Array(size/Math.pow(2,ri+1)).fill(0).map((_,mi)=>({id:uid(),p1:ri===0?slots[mi*2]:null,p2:ri===0?slots[mi*2+1]:null,s1:null,s2:null,winner:null,completed:false,bye:false}))});return{size,rounds,matches}}
function autoAdvance(){if(!state.current)return;state.current.rounds.forEach((r,ri)=>state.current.matches[r].forEach((m,mi)=>{if(ri===0&&!m.completed&&((m.p1&&!m.p2)||(!m.p1&&m.p2))){m.winner=m.p1||m.p2;m.completed=true;m.bye=true;}if(m.completed&&m.winner&&ri<state.current.rounds.length-1){const nextR=state.current.rounds[ri+1],next=state.current.matches[nextR][Math.floor(mi/2)];if(mi%2===0)next.p1=m.winner;else next.p2=m.winner;}}));}
function playerName(id){return state.players.find(p=>p.id===id)?.name||'Offen'}
function renderCurrent(){autoAdvance();const c=state.current;if(!c){$('currentDayInfo').textContent='Kein Spieltag gestartet';$('currentStatus').textContent='Bereit';$('bracket').innerHTML='<div class="empty-state">Der Admin wählt die anwesenden Spieler aus und startet danach die Auslosung.</div>';$('finishBox').hidden=true;return}$('currentDayInfo').textContent=`${c.date||''} · ${c.attendees.length} Teilnehmer · ${state.config.out}`;$('currentStatus').textContent='Läuft';$('bracket').innerHTML=c.rounds.map(r=>`<div class="round-column"><h3>${r}</h3>${c.matches[r].map((m,i)=>matchHtml(r,m,i)).join('')}</div>`).join('');document.querySelectorAll('[data-save-match]').forEach(b=>b.onclick=()=>saveMatch(b.dataset.round,Number(b.dataset.index)));const final=c.matches.Finale?.[0];$('finishBox').hidden=!(isAdmin&&final?.completed);}
function matchHtml(r,m,i){const settings=state.config.rounds?.[r]||{sets:1,legs:3};const ready=m.p1&&m.p2&&!m.completed;return `<div class="match-card"><div class="match-title">${r} ${i+1} · ${settings.sets>1?`First to ${settings.sets} Sets / ${settings.legs} Legs`:`First to ${settings.legs} Legs`}</div><div class="match-player ${m.winner===m.p1?'winner':''}"><span>${m.p1?esc(playerName(m.p1)):'—'}</span><input id="s1-${m.id}" type="number" min="0" value="${m.s1??''}" ${!ready?'disabled':''}></div><div class="match-player ${m.winner===m.p2?'winner':''}"><span>${m.p2?esc(playerName(m.p2)):'—'}</span><input id="s2-${m.id}" type="number" min="0" value="${m.s2??''}" ${!ready?'disabled':''}></div>${m.bye?'<div class="bye">Freilos – kein Matchsiegpunkt</div>':`<button data-save-match="1" data-round="${r}" data-index="${i}" ${!ready||!isAdmin?'disabled':''}>Ergebnis speichern</button>`}</div>`}
async function saveMatch(r,i){const m=state.current.matches[r][i],a=Number($(`s1-${m.id}`).value),b=Number($(`s2-${m.id}`).value);if(a===b||a<0||b<0)return toast('Bitte ein eindeutiges Ergebnis eingeben.');m.s1=a;m.s2=b;m.winner=a>b?m.p1:m.p2;m.completed=true;m.bye=false;autoAdvance();await save();toast('Ergebnis gespeichert.');}
function placementPoints(n,stage){const tables=n>=13?{winner:20,final:15,semi:11,quarter:7,early:3}:n>=9?{winner:18,final:13,semi:9,quarter:5,early:3}:n>=5?{winner:15,final:10,semi:6,quarter:2,early:2}:{winner:10,final:6,semi:2,quarter:2,early:2};return tables[stage]||tables.early}
function getPlacements(c){const out={};const rounds=c.rounds;rounds.forEach((r,ri)=>c.matches[r].forEach(m=>{if(!m.completed)return;const loser=m.winner===m.p1?m.p2:m.p1;if(loser){let stage='early';if(r==='Finale')stage='final';else if(r==='Halbfinale')stage='semi';else if(r==='Viertelfinale')stage='quarter';out[loser]=stage;}if(r==='Finale')out[m.winner]='winner'}));return out}
async function finishDay(){const c=state.current,final=c?.matches?.Finale?.[0];if(!final?.completed)return;const placements=getPlacements(c),stats={};c.attendees.forEach(id=>stats[id]={wins:0,legsFor:0,legsAgainst:0});c.rounds.forEach(r=>c.matches[r].forEach(m=>{if(!m.completed||m.bye||!m.p1||!m.p2)return;stats[m.winner].wins++;stats[m.p1].legsFor+=m.s1;stats[m.p1].legsAgainst+=m.s2;stats[m.p2].legsFor+=m.s2;stats[m.p2].legsAgainst+=m.s1;}));c.attendees.forEach(id=>{const old=state.ranking[id]||{};const base=placementPoints(c.attendees.length,placements[id]||'early');state.ranking[id]={days:(old.days||0)+1,wins:(old.wins||0)+stats[id].wins,titles:(old.titles||0)+(placements[id]==='winner'?1:0),legsFor:(old.legsFor||0)+stats[id].legsFor,legsAgainst:(old.legsAgainst||0)+stats[id].legsAgainst,points:(old.points||0)+base+stats[id].wins};});state.days.push({...c,finishedAt:new Date().toISOString()});state.current=null;await save();toast('Spieltag abgeschlossen und Rangliste aktualisiert.');}

document.querySelectorAll('.serie-tabs button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.serie-tabs button').forEach(x=>x.classList.toggle('active',x===b));document.querySelectorAll('.serie-panel').forEach(x=>x.classList.toggle('active',x.id===`tab-${b.dataset.tab}`))});
$('saveConfigBtn').onclick=async()=>{state.config.name=$('configName').value.trim()||'Vereins-Premier-League';state.config.maxPlayers=Math.min(16,Math.max(3,Number($('maxPlayers').value)||16));state.config.out=$('gameOut').value;state.config.rounds={};document.querySelectorAll('#roundSettings input').forEach(i=>{state.config.rounds[i.dataset.round]??={};state.config.rounds[i.dataset.round][i.dataset.key]=Math.max(1,Number(i.value)||1)});await save();toast('Einstellungen gespeichert.')};
$('addPlayerBtn').onclick=async()=>{const name=$('playerName').value.trim();if(!name)return;if(state.players.length>=Math.min(16,state.config.maxPlayers||16))return toast('Maximale Teilnehmerzahl erreicht.');if(state.players.some(p=>p.name.toLowerCase()===name.toLowerCase()))return toast('Spieler ist bereits vorhanden.');state.players.push({id:uid(),name});$('playerName').value='';await save()};
$('startDayBtn').onclick=async()=>{if(state.current)return toast('Es läuft bereits ein Spieltag.');const ids=[...document.querySelectorAll('[data-attend]:checked')].map(x=>x.dataset.attend);if(ids.length<3)return toast('Mindestens 3 Spieler müssen anwesend sein.');if(ids.length>16)return toast('Maximal 16 Spieler möglich.');const bracket=makeBracket(ids,$('drawMode').value,$('byeMode').value);state.current={id:uid(),date:$('dayDate').value||new Date().toISOString().slice(0,10),attendees:ids,startedAt:new Date().toISOString(),...bracket};autoAdvance();await save();document.querySelector('[data-tab="spieltag"]').click();toast('Spieltag ausgelost.')};
$('finishDayBtn').onclick=finishDay;$('dayDate').value=new Date().toISOString().slice(0,10);
load().catch(e=>{console.error(e);toast('Daten konnten nicht geladen werden.')});
