import { db, getLogin } from './auth-utils.js';
import { doc, getDoc, setDoc, serverTimestamp, collection, getDocs } from 'https://www.gstatic.com/firebasejs/10.12.0/firebase-firestore.js';

const REF=doc(db,'vereinsspielserie','hauptserie');
const MODES={premier:'Premier League',swiss:'Schweizer System',doubleko:'Doppel-K.-o.',groupsko:'Gruppen + K.-o.'};
const allowedRoles=['mitglied','captain','kassenwart'];
const login=getLogin();
const isAdmin=['admin','captain'].includes(String(login?.rolle||'').toLowerCase());
const $=id=>document.getElementById(id);
let state={members:[],seasons:[],activeSeasonId:null,current:null};

const uid=()=>crypto.randomUUID?.()||Math.random().toString(36).slice(2);
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function toast(m){const t=$('toast');t.textContent=m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2600)}
function season(){return state.seasons.find(s=>s.id===state.activeSeasonId)||state.seasons[0]||null}
function blankSeason(name='Saison 2026/27'){return{id:uid(),name,createdAt:new Date().toISOString(),ranking:{},days:[]}}
async function save(){await setDoc(REF,{...state,updatedAt:serverTimestamp()});renderAll()}
async function load(){const snap=await getDoc(REF);if(snap.exists())state={...state,...snap.data()};if(!state.seasons?.length){const s=blankSeason();state.seasons=[s];state.activeSeasonId=s.id;await save()}await syncMembers(false);renderAll()}

async function syncMembers(show=true){
  const qs=await getDocs(collection(db,'mitglieder'));
  const next=[];
  qs.forEach(d=>{const x=d.data();const role=String(x.rolle||'').toLowerCase();if(x.aktiv===true&&allowedRoles.includes(role)){next.push({id:d.id,name:x.nickname||x.spitzname||x.benutzername||d.id,rolle:role})}});
  next.sort((a,b)=>a.name.localeCompare(b.name,'de'));
  state.members=next;
  const s=season();if(s){s.ranking??={};next.forEach(m=>s.ranking[m.id]??=emptyStats())}
  await setDoc(REF,{...state,updatedAt:serverTimestamp()});
  if(show)toast(`${next.length} Spieler synchronisiert.`)
}
function emptyStats(){return{points:0,days:0,wins:0,titles:0,legsFor:0,legsAgainst:0,byMode:{},history:[]}}
function statFor(s,id,mode='all'){const base=s.ranking?.[id]||emptyStats();return mode==='all'?base:{...emptyStats(),...(base.byMode?.[mode]||{}),history:(base.history||[]).filter(h=>h.mode===mode)}}
function rankingRows(){const s=season(),filter=$('modeFilter')?.value||'all';return state.members.map(m=>({m,st:statFor(s,m.id,filter)})).sort((a,b)=>b.st.points-a.st.points||b.st.titles-a.st.titles||(b.st.legsFor-b.st.legsAgainst)-(a.st.legsFor-a.st.legsAgainst)||a.m.name.localeCompare(b.m.name,'de'))}

function renderAll(){document.querySelectorAll('.admin-only').forEach(el=>el.hidden=!isAdmin);renderSeason();renderRanking();renderAttendance();renderCurrent();renderHistory()}
function renderSeason(){const s=season();$('seasonTitle').textContent=s?.name||'Keine Saison';$('seasonSelect').innerHTML=state.seasons.map(x=>`<option value="${x.id}" ${x.id===state.activeSeasonId?'selected':''}>${esc(x.name)}</option>`).join('');const rows=rankingRows();$('summaryPlayers').textContent=state.members.length;$('summaryDays').textContent=s?.days?.length||0;$('summaryLeader').textContent=rows[0]?.st.points>0?rows[0].m.name:'–';$('summaryMode').textContent=s?.days?.length?MODES[s.days[s.days.length-1].mode]:'–'}
function renderRanking(){const rows=rankingRows();$('rankingBody').innerHTML=rows.length?rows.map((x,i)=>`<tr data-player="${x.m.id}"><td>${i+1}</td><td><strong>${esc(x.m.name)}</strong><br><small>${esc(x.m.rolle)}</small></td><td>${x.st.days||0}</td><td>${x.st.wins||0}</td><td>${x.st.titles||0}</td><td>${x.st.legsFor||0}:${x.st.legsAgainst||0}</td><td>${(x.st.legsFor||0)-(x.st.legsAgainst||0)}</td><td><strong>${x.st.points||0}</strong></td></tr>`).join(''):'<tr><td colspan="8">Noch keine spielberechtigten Mitglieder vorhanden.</td></tr>';document.querySelectorAll('[data-player]').forEach(r=>r.onclick=()=>openProfile(r.dataset.player))}
function renderAttendance(){$('attendanceList').innerHTML=state.members.length?state.members.map(m=>`<label class="attendance-row"><span>${esc(m.name)} <small>(${m.rolle})</small></span><input type="checkbox" data-attend="${m.id}" checked></label>`).join(''):'<p class="hint">Noch keine Mitglieder mit passender Rolle gefunden.</p>'}

function bracketSize(n){return n<=4?4:n<=8?8:16}
function shuffle(a){a=[...a];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function memberName(id){return state.members.find(m=>m.id===id)?.name||'Offen'}
function makeKO(ids,mode){const size=bracketSize(ids.length),slots=shuffle(ids).concat(Array(size-ids.length).fill(null));const names=size===16?['Achtelfinale','Viertelfinale','Halbfinale','Finale']:size===8?['Viertelfinale','Halbfinale','Finale']:['Halbfinale','Finale'];const matches={};names.forEach((r,ri)=>matches[r]=Array(size/2**(ri+1)).fill(0).map((_,i)=>({id:uid(),p1:ri?null:slots[i*2],p2:ri?null:slots[i*2+1],s1:null,s2:null,winner:null,completed:false,bye:false})));return{engine:'ko',mode,rounds:names,matches,size}}
function autoAdvance(c){c.rounds.forEach((r,ri)=>c.matches[r].forEach((m,mi)=>{if(ri===0&&!m.completed&&((m.p1&&!m.p2)||(!m.p1&&m.p2))){m.winner=m.p1||m.p2;m.completed=true;m.bye=true}if(m.completed&&m.winner&&ri<c.rounds.length-1){const n=c.matches[c.rounds[ri+1]][Math.floor(mi/2)];if(mi%2===0)n.p1=m.winner;else n.p2=m.winner}}))}
function swissStandings(c){const s={};c.attendees.forEach(id=>s[id]={id,mp:0,wins:0,legsFor:0,legsAgainst:0,opponents:[]});(c.swissMatches||[]).flat().forEach(m=>{if(!m.completed)return;if(m.bye){s[m.p1].mp+=2;s[m.p1].wins++;return}s[m.p1].legsFor+=m.s1;s[m.p1].legsAgainst+=m.s2;s[m.p2].legsFor+=m.s2;s[m.p2].legsAgainst+=m.s1;s[m.p1].opponents.push(m.p2);s[m.p2].opponents.push(m.p1);s[m.winner].mp+=2;s[m.winner].wins++});return Object.values(s).sort((a,b)=>b.mp-a.mp||(b.legsFor-b.legsAgainst)-(a.legsFor-a.legsAgainst)||b.legsFor-a.legsFor)}
function pairSwiss(c){const played=new Set();(c.swissMatches||[]).flat().forEach(m=>{if(m.p1&&m.p2)played.add([m.p1,m.p2].sort().join('|'))});let pool=swissStandings(c).map(x=>x.id),matches=[];while(pool.length){const p1=pool.shift();if(!pool.length){matches.push({id:uid(),p1,p2:null,s1:1,s2:0,winner:p1,completed:true,bye:true});break}let idx=pool.findIndex(p2=>!played.has([p1,p2].sort().join('|')));if(idx<0)idx=0;const p2=pool.splice(idx,1)[0];matches.push({id:uid(),p1,p2,s1:null,s2:null,winner:null,completed:false,bye:false})}c.swissMatches.push(matches)}

function renderCurrent(){const c=state.current;if(!c){$('currentDayTitle').textContent='Aktueller Spieltag';$('currentDayInfo').textContent='Kein Spieltag gestartet.';$('currentStatus').textContent='Bereit';$('dayWorkspace').innerHTML='<div class="empty-state">Der Admin wählt im Bereich Verwaltung die anwesenden Spieler und den Turniermodus aus.</div>';return}$('currentDayTitle').textContent=MODES[c.mode];$('currentDayInfo').textContent=`${c.date} · ${c.attendees.length} Teilnehmer · ${c.out} · First to ${c.legsToWin} Legs`;$('currentStatus').textContent='Läuft';if(c.engine==='ko')renderKO(c);else if(c.engine==='swiss')renderSwiss(c);else renderManual(c)}
function renderKO(c){autoAdvance(c);$('dayWorkspace').innerHTML=`<div class="bracket">${c.rounds.map(r=>`<div class="round-column"><h3>${r}</h3>${c.matches[r].map((m,i)=>koMatch(r,m,i)).join('')}</div>`).join('')}</div><div class="workspace-actions admin-only"><button id="finishCurrent" class="primary">Spieltag abschließen</button></div>`;document.querySelectorAll('[data-ko-save]').forEach(b=>b.onclick=()=>saveKOMatch(b.dataset.round,+b.dataset.index));const final=c.matches[c.rounds.at(-1)][0];$('finishCurrent').disabled=!final?.completed;$('finishCurrent').onclick=finishCurrent}
function koMatch(r,m,i){const ready=m.p1&&m.p2&&!m.completed;return`<div class="match-card"><small>${r} ${i+1}</small><div class="match-player ${m.winner===m.p1?'winner':''}"><span>${m.p1?esc(memberName(m.p1)):'—'}</span><input id="a-${m.id}" type="number" min="0" value="${m.s1??''}" ${!ready||!isAdmin?'disabled':''}></div><div class="match-player ${m.winner===m.p2?'winner':''}"><span>${m.p2?esc(memberName(m.p2)):'—'}</span><input id="b-${m.id}" type="number" min="0" value="${m.s2??''}" ${!ready||!isAdmin?'disabled':''}></div>${m.bye?'<div class="bye">Freilos</div>':`<button data-ko-save="1" data-round="${r}" data-index="${i}" ${!ready||!isAdmin?'disabled':''}>Ergebnis speichern</button>`}</div>`}
async function saveKOMatch(r,i){const m=state.current.matches[r][i],a=+$(`a-${m.id}`).value,b=+$(`b-${m.id}`).value;if(a===b||a<0||b<0)return toast('Bitte ein eindeutiges Ergebnis eintragen.');m.s1=a;m.s2=b;m.winner=a>b?m.p1:m.p2;m.completed=true;autoAdvance(state.current);await save();toast('Ergebnis gespeichert.')}

function renderSwiss(c){const standings=swissStandings(c),round=c.swissMatches.length,current=c.swissMatches.at(-1)||[];const roundDone=current.length&&current.every(m=>m.completed);$('dayWorkspace').innerHTML=`<div class="swiss-header"><h3>Runde ${round} von ${c.totalRounds}</h3><span class="pill">Schweizer System</span></div><div class="table-scroll"><table class="swiss-table"><thead><tr><th>#</th><th>Spieler</th><th>MP</th><th>Siege</th><th>Leg-Diff.</th></tr></thead><tbody>${standings.map((x,i)=>`<tr><td>${i+1}</td><td>${esc(memberName(x.id))}</td><td>${x.mp}</td><td>${x.wins}</td><td>${x.legsFor-x.legsAgainst}</td></tr>`).join('')}</tbody></table></div><h3>Paarungen Runde ${round}</h3>${current.map((m,i)=>swissMatch(m,i)).join('')}<div class="workspace-actions admin-only">${round<c.totalRounds?`<button id="nextSwiss" class="primary" ${!roundDone?'disabled':''}>Nächste Runde auslosen</button>`:`<button id="finishCurrent" class="primary" ${!roundDone?'disabled':''}>Spieltag abschließen</button>`}</div>`;document.querySelectorAll('[data-swiss-save]').forEach(b=>b.onclick=()=>saveSwissMatch(+b.dataset.index));if($('nextSwiss'))$('nextSwiss').onclick=async()=>{pairSwiss(c);await save()};if($('finishCurrent'))$('finishCurrent').onclick=finishCurrent}
function swissMatch(m,i){if(m.bye)return`<div class="swiss-match"><strong>${esc(memberName(m.p1))}</strong> – Freilos</div>`;return`<div class="swiss-match"><div class="match-player"><span>${esc(memberName(m.p1))}</span><input id="sa-${m.id}" type="number" min="0" value="${m.s1??''}" ${m.completed||!isAdmin?'disabled':''}></div><div class="match-player"><span>${esc(memberName(m.p2))}</span><input id="sb-${m.id}" type="number" min="0" value="${m.s2??''}" ${m.completed||!isAdmin?'disabled':''}></div><button data-swiss-save="1" data-index="${i}" ${m.completed||!isAdmin?'disabled':''}>Ergebnis speichern</button></div>`}
async function saveSwissMatch(i){const m=state.current.swissMatches.at(-1)[i],a=+$(`sa-${m.id}`).value,b=+$(`sb-${m.id}`).value;if(a===b||a<0||b<0)return toast('Bitte ein eindeutiges Ergebnis eintragen.');m.s1=a;m.s2=b;m.winner=a>b?m.p1:m.p2;m.completed=true;await save()}

function renderManual(c){$('dayWorkspace').innerHTML=`<div class="empty-state"><h3>${MODES[c.mode]}</h3><p>${c.mode==='doubleko'?'Die Partien werden im Doppel-K.-o. gespielt. Nach dem letzten Spiel trägst du hier die endgültigen Platzierungen ein.':'Nach Gruppenphase und K.-o.-Runde trägst du hier die endgültigen Platzierungen ein.'}</p></div><div class="manual-grid">${c.attendees.map(id=>`<div class="manual-row"><strong>#</strong><span>${esc(memberName(id))}</span><select data-place="${id}">${c.attendees.map((_,i)=>`<option value="${i+1}">${i+1}. Platz</option>`).join('')}</select></div>`).join('')}</div><div class="workspace-actions admin-only"><button id="finishCurrent" class="primary">Platzierungen prüfen und Spieltag abschließen</button></div>`;$('finishCurrent').onclick=finishCurrent}

function placementPoints(n,place){const group=n>=13?[20,15,11,11,7,7,7,7,3]:n>=9?[18,13,9,9,5,5,5,5,3]:n>=5?[15,10,6,6,2]:[10,6,2];return group[Math.min(place-1,group.length-1)]||group.at(-1)}
function resultsFor(c){if(c.engine==='swiss')return swissStandings(c).map((x,i)=>({id:x.id,place:i+1,wins:x.wins,legsFor:x.legsFor,legsAgainst:x.legsAgainst}));if(c.engine==='manual'){const vals=[...document.querySelectorAll('[data-place]')].map(x=>({id:x.dataset.place,place:+x.value}));if(new Set(vals.map(x=>x.place)).size!==vals.length)throw new Error('Jede Platzierung darf nur einmal vergeben werden.');return vals.sort((a,b)=>a.place-b.place).map(x=>({...x,wins:0,legsFor:0,legsAgainst:0}))}const losses={},stats={};c.attendees.forEach(id=>stats[id]={wins:0,legsFor:0,legsAgainst:0});c.rounds.forEach(r=>c.matches[r].forEach(m=>{if(!m.completed)return;const loser=m.winner===m.p1?m.p2:m.p1;if(loser)losses[loser]=r;if(!m.bye&&m.p1&&m.p2){stats[m.winner].wins++;stats[m.p1].legsFor+=m.s1;stats[m.p1].legsAgainst+=m.s2;stats[m.p2].legsFor+=m.s2;stats[m.p2].legsAgainst+=m.s1}}));const final=c.matches[c.rounds.at(-1)][0],winner=final.winner;return c.attendees.map(id=>{let place=id===winner?1:losses[id]==='Finale'?2:losses[id]==='Halbfinale'?3:losses[id]==='Viertelfinale'?5:9;return{id,place,...stats[id]}}).sort((a,b)=>a.place-b.place)}
async function finishCurrent(){try{const c=state.current,s=season(),results=resultsFor(c);results.forEach(r=>{const base=s.ranking[r.id]||emptyStats(),pts=placementPoints(c.attendees.length,r.place)+(r.wins||0);base.points+=pts;base.days++;base.wins+=r.wins||0;base.titles+=r.place===1?1:0;base.legsFor+=r.legsFor||0;base.legsAgainst+=r.legsAgainst||0;base.byMode??={};const bm=base.byMode[c.mode]||emptyStats();bm.points+=pts;bm.days++;bm.wins+=r.wins||0;bm.titles+=r.place===1?1:0;bm.legsFor+=r.legsFor||0;bm.legsAgainst+=r.legsAgainst||0;base.byMode[c.mode]=bm;base.history??=[];base.history.push({dayId:c.id,date:c.date,mode:c.mode,place:r.place,points:pts});s.ranking[r.id]=base});const day={...c,results,finishedAt:new Date().toISOString()};s.days.push(day);state.current=null;await save();toast('Spieltag abgeschlossen und Punkte gebucht.')}catch(e){toast(e.message||'Spieltagsabschluss nicht möglich.')}}

function renderHistory(){const s=season(),days=[...(s?.days||[])].reverse();$('historyList').innerHTML=days.length?days.map(d=>{const top=[...(d.results||[])].sort((a,b)=>a.place-b.place).slice(0,3);return`<article class="history-card"><div class="history-card-head"><div><h3>${esc(d.date)}</h3><p>${d.attendees.length} Teilnehmer · ${esc(d.out||'')}</p></div><span class="mode-badge">${MODES[d.mode]}</span></div><div class="history-podium">${top.map(x=>`${x.place}. ${esc(memberName(x.id))}`).join(' · ')}</div></article>`}).join(''):'<div class="empty-state">Noch keine abgeschlossenen Spieltage.</div>'}
function openProfile(id){const m=state.members.find(x=>x.id===id),st=statFor(season(),id,$('modeFilter').value);$('profileContent').innerHTML=`<h2>${esc(m.name)}</h2><p>${esc(m.rolle)}</p><div class="profile-stats"><div><strong>${st.points||0}</strong>Punkte</div><div><strong>${st.days||0}</strong>Spieltage</div><div><strong>${st.wins||0}</strong>Siege</div><div><strong>${st.titles||0}</strong>Titel</div><div><strong>${st.legsFor||0}:${st.legsAgainst||0}</strong>Legs</div><div><strong>${(st.legsFor||0)-(st.legsAgainst||0)}</strong>Leg-Diff.</div></div><div class="profile-history"><h3>Letzte Spieltage</h3>${(st.history||[]).slice(-8).reverse().map(h=>`<div class="profile-history-row"><span>${esc(h.date)}</span><span>${MODES[h.mode]}</span><strong>+${h.points}</strong></div>`).join('')||'<p>Keine Ergebnisse.</p>'}</div>`;$('profileModal').hidden=false}

$('seasonSelect').onchange=()=>{state.activeSeasonId=$('seasonSelect').value;renderAll()};$('modeFilter').onchange=renderRanking;$('closeProfile').onclick=()=>$('profileModal').hidden=true;$('profileModal').onclick=e=>{if(e.target===$('profileModal'))$('profileModal').hidden=true};
$('createSeasonBtn').onclick=async()=>{const name=$('newSeasonName').value.trim();if(!name)return toast('Bitte einen Saisonnamen eingeben.');const s=blankSeason(name);state.members.forEach(m=>s.ranking[m.id]=emptyStats());state.seasons.push(s);state.activeSeasonId=s.id;$('newSeasonName').value='';await save();toast('Neue Saison angelegt.')};$('syncMembersBtn').onclick=()=>syncMembers(true);
$('dayMode').onchange=()=>{$('swissRoundsWrap').hidden=$('dayMode').value!=='swiss'};
$('startDayBtn').onclick=async()=>{if(state.current)return toast('Es läuft bereits ein Spieltag.');const ids=[...document.querySelectorAll('[data-attend]:checked')].map(x=>x.dataset.attend),mode=$('dayMode').value;if(ids.length<3)return toast('Mindestens 3 Spieler müssen anwesend sein.');if(ids.length>16)return toast('Maximal 16 Spieler möglich.');const common={id:uid(),date:$('dayDate').value||new Date().toISOString().slice(0,10),mode,out:$('gameOut').value,legsToWin:+$('legsToWin').value||3,attendees:ids,startedAt:new Date().toISOString()};if(mode==='premier')state.current={...common,...makeKO(ids,mode)};else if(mode==='swiss'){state.current={...common,engine:'swiss',totalRounds:+$('swissRounds').value||4,swissMatches:[]};pairSwiss(state.current)}else state.current={...common,engine:'manual'};await save();document.querySelector('[data-tab="spieltag"]').click();toast('Spieltag gestartet.')};

document.querySelectorAll('.serie-tabs button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.serie-tabs button').forEach(x=>x.classList.toggle('active',x===b));document.querySelectorAll('.serie-panel').forEach(x=>x.classList.toggle('active',x.id===`tab-${b.dataset.tab}`))});
$('dayDate').value=new Date().toISOString().slice(0,10);
load().catch(e=>{console.error(e);toast('Daten konnten nicht geladen werden. Prüfe die Firestore-Regeln.')});
